[workspace]

[package]
name = "dlsm-sync"
description = "sync"
version = "0.0.1"
edition = "2021"
rust-version = "1.75"
license = "TBD"
authors = ["DLSM Authors"]
repository = "https://github.com/chestnutsj/dlsm-sync"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
unused_must_use = "deny"
missing_debug_implementations = "warn"
missing_docs = "warn"
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(loom)'] }

[lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
todo = "deny"
dbg_macro = "deny"
unimplemented = "deny"
unwrap_used = "warn"
expect_used = "warn"


[dev-dependencies]
dlsm-shm = { git = "https://github.com/chestnutsj/dlsm-shm.git", branch = "master" }

# [patch."https://github.com/chestnutsj/dlsm-shm.git"]
# dlsm-shm = { path = "../dlsm-shm" }

[target.'cfg(loom)'.dependencies]
loom = "0.7"

[profile.release]
opt-level = 3
lto = "thin"
codegen-units = 1
